### ISSUE TITLE
Node-pty installation issues!

### ISSUE THREAD

**Issue by rahul-technogetic** [piyushgarg-dev/cloud-ide#4]
The node-pty package isn't installing in the Windows based Systems!,
Mainly due to to the issue related to python/path so if others are getting the same issue then piyush bro could you just Pin a comment on that video about this!

https://github.com/microsoft/node-pty/issues/439

**Comment by ruru-m07** [comment]
> The node-pty package isn't installing in the Windows based Systems!,
> Mainly due to to the issue related to python/path so if others are getting the same issue then piyush bro could you just Pin a comment on that video about this!
> 
> https://github.com/microsoft/node-pty/issues/439

I face the same issue in my windows soo I use GitHub codespace that is based on Ubuntu and it works perfectly fine

**Comment by rahul-technogetic** [comment]
great then! thanx @ruru-m07
